import type {PlayView} from '@shared/play-engine';
export function discovery(v:PlayView):{text:string;flow:string[]}{
  if(v.kind==='light')return v.stage===1?{text:'Ai recunoscut aceeași formă, chiar dacă piesele au alte mărimi.',flow:['Contur','Compară','Aceeași formă']}:v.stage===2?{text:'Ai rotit piesa până s-a potrivit. Forma ei a rămas aceeași.',flow:['Piesă','Rotire','Potrivire']}:{text:'Ai închis circuitul. Curentul are un drum dus și întors prin bec.',flow:['Baterie','Bec aprins','Înapoi la baterie']};
  if(v.kind==='signal'){
    const record=v.records.find(r=>r.received);
    return v.stage===1?{text:'Ai păstrat o ipoteză. Intensitatea semnalului nu ne spune cine îl trimite.',flow:['Semnal','Ipoteză','Urmează probele']}:v.stage===2?{text:'Ai schimbat ritmul trimis. Compară răspunsurile pentru a vedea dacă se schimbă și ele.',flow:record?[record.input.join('–'),'Trimis → primit',record.received!.join('–')]:['Trimitere','Recepție','Compară']}:{text:'Ai legat o concluzie de o observație. Verifică dacă observația susține explicația.',flow:['Observație','Compară','Concluzie']};
  }
  if(v.kind==='pilot')return {text:v.stage===3?(v.beforeDecision===v.decision?'În această probă, decizia a rămas aceeași. O schimbare de regulă nu schimbă orice rezultat.':'Aceeași situație a produs altă decizie după schimbarea regulii.'):v.stage===2?'Ai rulat ambele probe. Pilotul urmează regulile primite, chiar dacă senzorii pot greși.':'Ai stabilit o regulă. Probele arată ce consecințe are.',flow:['Regulă',v.case==='agree'?'Senzori de acord':'Senzori diferiți',({incomplete:'Regulă incompletă',propose:'Propune',confirm:'Cere acordul',execute:'Execută'})[v.decision]]};
  return {text:v.stage===1?(v.scanKind==='fine'?'Ai ales detaliul unei singure zone și ai folosit ambele credite.':'Ai cercetat ansamblul și ai păstrat energie pentru următoarea decizie.'):v.stage===2?(v.protection==='protect'?'Obturatorul a oprit înregistrarea prin nor. Pauza lasă date lipsă, nu măsurători curate.':'Sonda a înregistrat și prin nor. Acele citiri pot fi tulburate.'):'Ai transmis un document, împreună cu limitele lui.',flow:v.stage===1?['Zonă','Scanare',`${v.credits} credite rămase`]:v.stage===2?['Nor',v.protection==='protect'?'Obturator închis':'Înregistrare','Raport']:['Document','Cu limitele lui','Echipajul următor']};
}
