/** Steaua Omenirii: measured Eleven v3 score, generated by assemble-steaua-score.mjs. */
export const STAR_SCORE = {
  "preshowDurationSec": 60,
  "epilogueDurationSec": 75,
  "videoDurationSec": 678.05,
  "stageWindows": [
    [
      106,
      129
    ],
    [
      205,
      229
    ],
    [
      323.5,
      355.5
    ]
  ],
  "musicSilence": {
    "phase": "play",
    "startSec": 368.9,
    "endSec": 382.2
  },
  "ignitionSec": 356.5,
  "questionSec": 369.2,
  "cometSec": 382.7,
  "revelationSec": 633
} as const;
