import type {MissionSnapshot} from '@shared/mission';
import type {ShowState} from '@shared/types';

export function createExperienceControl(deps:{snapshot():{state:ShowState|null;role:string|null}}){
  const toolbar=document.querySelector('.presentation-toolbar');if(!toolbar)return;
  const open=document.createElement('button');open.type='button';open.className='mission-tools-button';open.textContent='Tutorial și echipaj';toolbar.append(open);
  const dialog=document.createElement('dialog');dialog.className='experience-control glass';dialog.setAttribute('aria-labelledby','experience-control-title');
  dialog.innerHTML=`<header><div><p class="eyebrow">PRIMUL MOMENT AL CĂLĂTORIEI</p><h2 id="experience-control-title">Nava vă recunoaște</h2><p>Tutorial separat de film. Probele nu consumă resursele misiunii.</p></div><button type="button" data-close>Închide</button></header><div class="experience-control-status" role="status"></div><h3>Participanții acestei sesiuni</h3><p>Bifează locurile ocupate, apoi aplică. Confirmările afișate provin din acțiuni reale.</p><div class="experience-control-seats"></div><div class="experience-control-actions"><button type="button" data-action="participants">Aplică participanții</button><button type="button" data-action="start">Începe tutorialul</button><button type="button" data-action="pause">Pauză</button><button type="button" data-action="resume">Continuă</button><button type="button" data-action="repeat">Repetă explicația</button><button type="button" data-action="next">Pasul următor</button><button type="button" data-action="skip">Sari peste tutorial</button><button type="button" data-action="launch">Predă Căpitanului și pornește</button></div><p class="experience-control-feedback" aria-live="polite"></p>`;
  document.body.append(dialog);const seats=dialog.querySelector<HTMLElement>('.experience-control-seats')!,status=dialog.querySelector<HTMLElement>('.experience-control-status')!,feedback=dialog.querySelector<HTMLElement>('.experience-control-feedback')!;
  let mission:MissionSnapshot|null=null,busy=false,dirty=false,lastRun='',refreshing=false;
  for(let i=1;i<=5;i++){const card=document.createElement('section'),title=document.createElement('h4');title.textContent=`Postul ${i}`;card.append(title);for(const z of ['A','B']){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span'),state=document.createElement('small');input.type='checkbox';input.value=`${i}${z}`;input.addEventListener('change',()=>{dirty=true;});text.textContent=`Zona ${z}`;state.dataset.seat=input.value;state.textContent='Se verifică';label.append(input,text,state);card.append(label);}seats.append(card);}
  function render(){const e=mission?.experience,role=deps.snapshot().role,editable=!!role&&role!=='viewer',idle=mission?.state.state==='idle'&&!mission?.suspended;
    status.textContent=!mission?'Se încarcă starea reală…':!e?'Tutorialul nu a fost pregătit.':e.active?`${e.paused?'În pauză · ':''}${({touch:'Recunoaștere',practice:'Proba comenzilor',cooperate:'Legătura echipajului',ready:'Pregătiți'})[e.step]} · ${e.participants.length} participanți · ${e.canContinue?'Pas confirmat':'Așteptăm contribuțiile'}`:e.status==='complete'?'Tutorial încheiat.':e.status==='skipped'?'Tutorial omis de operator.':'Pregătire';
    for(const input of seats.querySelectorAll<HTMLInputElement>('input')){if(!dirty)input.checked=!!e?.participants.includes(input.value);input.disabled=busy||!editable||!idle;const state=seats.querySelector<HTMLElement>(`[data-seat="${input.value}"]`)!;state.textContent=!e?'Fără confirmare':!e.participants.includes(input.value)?'Loc liber':e.observed.includes(input.value)?'Privește':`${e.touched.includes(input.value)?'✓':'○'} Atingere · ${e.practiced.includes(input.value)?'✓':'○'} Probă · ${e.linked.includes(input.value)?'✓':'○'} Legătură`;}
    for(const button of dialog.querySelectorAll<HTMLButtonElement>('[data-action]')){const a=button.dataset.action;button.disabled=busy||!editable||!idle||!mission||(a==='start'&&!!e?.active)||(a==='pause'&&(!e?.active||e.paused))||(a==='resume'&&(!e?.active||!e.paused))||(a==='repeat'&&!e?.active)||(a==='skip'&&e?.status==='skipped')||(a==='next'&&(!e?.active||!e.canContinue||e.paused||e.step==='ready'))||(a==='launch'&&(!e||e.paused||(e.status!=='skipped'&&e.step!=='ready')));}
  }
  async function refresh(){if(refreshing)return;refreshing=true;try{const r=await fetch('/api/mission',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Starea tutorialului nu este disponibilă.');const data=await r.json();mission=data.mission??data;if(mission?.runId!==lastRun){lastRun=mission?.runId??'';dirty=false;}render();}catch(e){feedback.textContent=e instanceof Error?e.message:String(e);}finally{refreshing=false;}}
  for(const button of dialog.querySelectorAll<HTMLButtonElement>('[data-action]'))button.addEventListener('click',async()=>{if(busy)return;busy=true;render();feedback.textContent='Se aplică…';try{const action=button.dataset.action;const r=await fetch('/api/experience/control',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='participants'?{participants:Array.from(seats.querySelectorAll<HTMLInputElement>('input:checked')).map(i=>i.value)}:{})})});const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.reason??data.error??'Comanda nu a fost acceptată.');dirty=false;await refresh();feedback.textContent='Comanda a fost confirmată.';}catch(e){feedback.textContent=e instanceof Error?e.message:String(e);}finally{busy=false;render();}});
  open.addEventListener('click',()=>{dialog.showModal();void refresh();});dialog.querySelector('[data-close]')!.addEventListener('click',()=>dialog.close());setInterval(()=>{if(dialog.open)void refresh();},700);
}
