import type {MissionSnapshot} from '@shared/mission';
import type {ShowState} from '@shared/types';
import {crewCharacter,characterPortrait} from '@shared/crew';

export function createExperienceControl(deps:{snapshot():{state:ShowState|null;role:string|null}}){
  const toolbar=document.querySelector('.presentation-toolbar');if(!toolbar)return;
  const open=document.createElement('button');open.type='button';open.className='mission-tools-button';open.textContent='Tutorial și echipaj';toolbar.append(open);
  const dialog=document.createElement('dialog');dialog.className='experience-control glass';dialog.setAttribute('aria-labelledby','experience-control-title');
  dialog.innerHTML=`<header><div><p class="eyebrow">PRIMUL MOMENT AL CĂLĂTORIEI</p><h2 id="experience-control-title">Nava vă recunoaște</h2><p>Tutorial separat de film. Probele nu consumă resursele misiunii.</p></div><button type="button" data-close>Închide</button></header><div class="experience-control-status" role="status"></div><h3>Participanții acestei sesiuni</h3><p>Participanții aleg și confirmă personajul pe jumătatea lor de tabletă. Un singur personaj confirmat este suficient; locurile libere nu blochează experiența.</p><div class="experience-control-seats"></div><div class="experience-control-actions"><button type="button" data-action="participants">Aplică participanții</button><button type="button" data-action="reopenCrew">Redeschide alegerea personajelor</button><button type="button" data-action="start">Începe tutorialul</button><button type="button" data-action="pause">Pauză</button><button type="button" data-action="resume">Continuă</button><button type="button" data-action="repeat">Repetă explicația</button><button type="button" data-action="next">Pasul următor</button><button type="button" data-action="skip">Sari peste tutorial</button><button type="button" data-action="launch">Predă Căpitanului și pornește</button></div><p class="experience-control-feedback" aria-live="polite"></p>`;
  document.body.append(dialog);const seats=dialog.querySelector<HTMLElement>('.experience-control-seats')!,status=dialog.querySelector<HTMLElement>('.experience-control-status')!,feedback=dialog.querySelector<HTMLElement>('.experience-control-feedback')!;
  let mission:MissionSnapshot|null=null,busy=false,dirty=false,lastRun='',refreshing=false;
  let tabletConnections:Array<{post?:number;connected:boolean}>|null=null, connectionError=false;
  const actions=dialog.querySelector<HTMLElement>('.experience-control-actions')!;
  const primary=document.createElement('button');primary.type='button';primary.className='experience-next';primary.dataset.action='start';
  const guidance=document.createElement('p');guidance.className='experience-next-guidance';guidance.setAttribute('role','status');
  const nextBlock=document.createElement('section');nextBlock.className='experience-next-block';nextBlock.append(primary,guidance);
  const tools=document.createElement('details'),toolsTitle=document.createElement('summary');tools.className='experience-secondary';toolsTitle.textContent='Oprește, repetă sau gestionează echipajul';tools.append(toolsTitle);
  actions.before(nextBlock,tools);tools.append(actions);
  const reopenNote=document.createElement('p');reopenNote.textContent='Redeschiderea păstrează personajele, dar reia pregătirea și șterge confirmările tutorialului.';tools.append(reopenNote);
  const journals=document.createElement('details'),journalTitle=document.createElement('summary'),journalList=document.createElement('div'),journalRefresh=document.createElement('button');
  journals.className='experience-journals';journalTitle.textContent='Jurnalele expediției';journalList.className='experience-journal-list';journalList.setAttribute('aria-live','polite');journalRefresh.type='button';journalRefresh.textContent='Actualizează lista jurnalelor';journals.append(journalTitle,journalList,journalRefresh);tools.after(journals);
  let journalBusy=false;
  const retryingPosts=new Set<number>();
  const journalFeedback=document.createElement('p');journalFeedback.setAttribute('role','status');journals.append(journalFeedback);
  function retryAllowed(post:number){const role=deps.snapshot().role;return !!role&&role!=='viewer'&&!busy&&!journalBusy&&!retryingPosts.has(post)&&!!mission&&['epilogue','ended'].includes(mission.state.state)&&!mission.suspended&&!connectionError&&!!tabletConnections?.some(tablet=>tablet.post===post&&tablet.connected);}
  function updateRetryButtons(){for(const button of journalList.querySelectorAll<HTMLButtonElement>('[data-retry-post]'))button.disabled=!retryAllowed(Number(button.dataset.retryPost));}
  async function retryJournal(post:number){if(!retryAllowed(post))return;const runId=mission!.runId;retryingPosts.add(post);updateRetryButtons();journalFeedback.textContent=`Cerem jurnalul postului ${post}…`;try{const response=await fetch('/api/mission/journal/retry',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({runId,post})});const result=await response.json();if(mission?.runId!==runId)return;if(!response.ok||result.ok!==true)throw new Error(result.reason??result.error??'Cererea de retrimitere nu a fost acceptată.');journalFeedback.textContent=`Postul ${post} · Cerere acceptată. Transferul poate dura câteva secunde; jurnalul este primit numai când apare linkul către fișier. Actualizează lista pentru confirmare.`;}catch(error){if(mission?.runId===runId)journalFeedback.textContent=error instanceof Error?error.message:String(error);}finally{retryingPosts.delete(post);updateRetryButtons();}}
  const addRetryButtons=()=>{for(const row of journalList.querySelectorAll<HTMLElement>('[data-missing-post]')){if(row.querySelector('button'))continue;const post=Number(row.dataset.missingPost),button=document.createElement('button');button.type='button';button.dataset.retryPost=String(post);button.textContent='Cere retrimiterea';button.setAttribute('aria-label',`Cere retrimiterea jurnalului pentru postul ${post}`);button.addEventListener('click',()=>void retryJournal(post));row.append(button);}updateRetryButtons();};
  async function refreshJournals(){if(journalBusy)return;journalBusy=true;journalRefresh.disabled=true;const runId=mission?.runId;journalList.textContent='Căutăm jurnalele salvate…';try{const response=await fetch('/api/certificates',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error('Lista jurnalelor nu este disponibilă. Încearcă din nou.');const data=await response.json() as {runs:Array<{run:string;files:Array<{post:number;url:string}>}>};if(mission?.runId!==runId){journalList.textContent='Grupul s-a schimbat. Actualizează lista.';return;}journalList.replaceChildren();const files=data.runs.find(run=>run.run===runId)?.files??[];const activePosts=[...new Set(mission?.experience?.participants.map(seat=>Number(seat[0]))??[])];for(const post of activePosts){const row=document.createElement('p'),file=files.find(item=>item.post===post);if(file){const link=document.createElement('a');link.href=file.url;link.target='_blank';link.rel='noopener';link.textContent=`Postul ${post} · Deschide jurnalul salvat`;row.append(link);}else {row.textContent=`Postul ${post} · Jurnalul nu a fost încă primit`;row.dataset.missingPost=String(post);}journalList.append(row);}if(!activePosts.length)journalList.textContent='Niciun participant confirmat în acest grup.';const note=document.createElement('p');note.textContent='Jurnalele sunt trimise de tablete după încheiere. Poți cere retrimiterea la final, de la o tabletă conectată. Actualizarea listei verifică dacă fișierul a fost primit.';journalList.append(note);}catch(error){journalList.textContent=error instanceof Error?error.message:String(error);}finally{journalBusy=false;journalRefresh.disabled=false;addRetryButtons();}}
  journalRefresh.addEventListener('click',()=>void refreshJournals());journals.addEventListener('toggle',()=>{if(journals.open)void refreshJournals();});
  for(let i=1;i<=5;i++){const card=document.createElement('section'),title=document.createElement('h4');title.textContent=`Postul ${i}`;card.append(title);for(const z of ['A','B']){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span'),state=document.createElement('small');input.type='checkbox';input.value=`${i}${z}`;input.addEventListener('change',()=>{dirty=true;});text.textContent=`Zona ${z}`;state.dataset.seat=input.value;state.textContent='Se verifică';label.append(input,text,state);card.append(label);}seats.append(card);}
  function render(){updateRetryButtons();const e=mission?.experience,role=deps.snapshot().role,editable=!!role&&role!=='viewer',idle=mission?.state.state==='idle'&&!mission?.suspended;
    const nextAction=e?.paused?'resume':!e?.active&&e?.status!=='skipped'&&e?.status!=='complete'?'start':e?.status==='skipped'||e?.step==='ready'?'launch':'next';
    primary.dataset.action=nextAction;primary.textContent=({resume:'Continuă tutorialul',start:'Începe tutorialul',launch:'Pornește călătoria',next:'Continuă cu pasul următor'})[nextAction];
    const completed=e?.step==='touch'?e.touched:e?.step==='practice'?e.practiced:e?.linked??[];
    const waiting=e?.participants.filter(seat=>!e.observed.includes(seat)&&!completed.includes(seat))??[];
    const missingPosts=!connectionError&&tabletConnections&&e?[...new Set(e.participants.map(seat=>Number(seat[0])))].filter(post=>!tabletConnections!.some(tablet=>tablet.post===post&&tablet.connected)):[];
    const readiness=deps.snapshot().state?.readiness??mission?.state.readiness;
    guidance.textContent=!e?'Se încarcă pregătirea…':!idle?'Călătoria este în desfășurare. Lista echipajului rămâne păstrată.':!e.participants.length?'Așteptăm primul personaj confirmat pe o tabletă.':missingPosts.length?`Refacem legătura cu postul ${missingPosts.join(', ')}. Personajele și progresul sunt păstrate.`:e.paused?'Tutorialul este în pauză. Continuă când grupul este pregătit.':e.active&&waiting.length&&e.step!=='ready'?`Mai așteptăm: ${waiting.map(seat=>`${crewCharacter(e.crew?.characters[seat])?.name??'Participant'} · ${seat}`).join(', ')}.`:nextAction==='launch'&&readiness&&!readiness.ready?readiness.reasons.join(' · '):e.crew?.open?`${e.participants.length} ${e.participants.length===1?'participant confirmat':'participanți confirmați'}. Pornește când întregul grup și-a ales personajul.`:'Echipajul este pregătit pentru următorul pas.';
    for(const card of seats.querySelectorAll('section')){const post=Number(card.querySelector('input')?.value[0]);let connection=card.querySelector<HTMLElement>('.experience-post-connection');if(!connection){connection=document.createElement('p');connection.className='experience-post-connection';card.querySelector('h4')!.after(connection);}const connected=tabletConnections?.some(tablet=>tablet.post===post&&tablet.connected),required=e?.participants.some(seat=>Number(seat[0])===post);connection.textContent=connectionError||!tabletConnections?'Conexiune necunoscută':connected?'Tabletă conectată':required?'Deconectată · progres păstrat':'Nicio tabletă conectată';connection.dataset.connected=String(!!connected);}
    status.textContent=!e?'Se încarcă starea reală…':e.crew?.open?`${e.participants.length} personaje confirmate · Alegerea este deschisă`:e.active?`${e.paused?'În pauză · ':''}${({touch:'Recunoaștere',practice:'Proba comenzilor',cooperate:'Legătura echipajului',ready:'Pregătiți'})[e.step]} · ${e.participants.length} participanți · ${e.canContinue?'Pas confirmat':'Așteptăm contribuțiile'}`:e.status==='complete'?'Tutorial încheiat.':e.status==='skipped'?'Tutorial omis de operator.':'Pregătire';
    for(const input of seats.querySelectorAll<HTMLInputElement>('input')){
      if(!dirty)input.checked=!!e?.participants.includes(input.value);
      input.disabled=!!e?.crew||busy||!editable||!idle;input.hidden=!!e?.crew;
      const character=crewCharacter(e?.crew?.characters[input.value]),label=input.closest('label')!;
      let image=label.querySelector<HTMLImageElement>('img');
      if(character){if(!image){image=document.createElement('img');image.className='control-crew-portrait';label.prepend(image);}image.src=characterPortrait(character.id);image.alt=character.name;}else image?.remove();
      label.querySelector('span')!.textContent=character?`${character.name} · ${input.value}`:`Zona ${input.value.slice(-1)}`;
      const state=seats.querySelector<HTMLElement>(`[data-seat="${input.value}"]`)!;
      state.textContent=!e?'Fără confirmare':!e.participants.includes(input.value)?'Loc liber':e.crew?.open?'Personaj confirmat':e.observed.includes(input.value)?'Privește':`${e.touched.includes(input.value)?'✓':'○'} Atingere · ${e.practiced.includes(input.value)?'✓':'○'} Probă · ${e.linked.includes(input.value)?'✓':'○'} Legătură`;
      let release=label.querySelector<HTMLButtonElement>('.crew-release-seat');
      if(character){if(!release){release=document.createElement('button');release.type='button';release.className='crew-release-seat';release.textContent='Eliberează locul';release.onclick=event=>{event.preventDefault();void submit('releaseSeat',input.value);};label.append(release);}release.disabled=busy||!editable||!idle||!e?.crew?.open;}else release?.remove();
    }
    for(const button of dialog.querySelectorAll<HTMLButtonElement>('[data-action]')){const a=button.dataset.action;button.hidden=a==='participants'?!!e?.crew:a==='reopenCrew'?!e?.crew:false;button.disabled=(a==='start'&&!e?.participants.length)||(a==='launch'&&!e?.participants.length)||(a==='reopenCrew'&&!!e?.crew?.open)||busy||!editable||!idle||!mission||(a==='start'&&!!e?.active)||(a==='pause'&&(!e?.active||e.paused))||(a==='resume'&&(!e?.active||!e.paused))||(a==='repeat'&&!e?.active)||(a==='skip'&&e?.status==='skipped')||(a==='next'&&(!e?.active||!e.canContinue||e.paused||e.step==='ready'))||(a==='launch'&&(!e||e.paused||(e.status!=='skipped'&&e.step!=='ready')));}
    if((nextAction==='start'||nextAction==='launch')&&missingPosts.length)primary.disabled=true;
    if(nextAction==='launch'&&readiness&&!readiness.ready)primary.disabled=true;
  }
  async function refresh(){if(refreshing)return;refreshing=true;try{const [result,inventory]=await Promise.allSettled([fetch('/api/mission',{credentials:'same-origin',cache:'no-store'}),fetch('/api/tablets',{credentials:'same-origin',cache:'no-store'})]);connectionError=inventory.status==='rejected'||!inventory.value.ok;if(!connectionError&&inventory.status==='fulfilled'){try{tabletConnections=(await inventory.value.json()).tablets;}catch{connectionError=true;}}if(result.status==='rejected'||!result.value.ok)throw new Error('Starea tutorialului nu poate fi actualizată.');const data=await result.value.json();mission=data.mission??data;if(mission?.runId!==lastRun){lastRun=mission?.runId??'';dirty=false;journalFeedback.textContent='';journalList.textContent='Grup nou. Actualizează lista pentru această expediție.';}render();}catch(e){feedback.textContent=e instanceof Error?e.message:String(e);}finally{refreshing=false;}}
  async function submit(action:string,seat?:string){if(busy)return;busy=true;render();feedback.textContent='Se aplică…';try{const r=await fetch('/api/experience/control',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,seat,runId:mission?.runId,...(action==='participants'?{participants:Array.from(seats.querySelectorAll<HTMLInputElement>('input:checked')).map(i=>i.value)}:{})})});const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.reason??data.error??'Comanda nu a fost acceptată.');dirty=false;await refresh();feedback.textContent='Comanda a fost confirmată.';}catch(e){feedback.textContent=e instanceof Error?e.message:String(e);}finally{busy=false;render();}}
  for(const button of dialog.querySelectorAll<HTMLButtonElement>('[data-action]'))button.addEventListener('click',()=>void submit(button.dataset.action!));
  open.addEventListener('click',()=>{render();dialog.showModal();void refresh();});dialog.querySelector('[data-close]')!.addEventListener('click',()=>dialog.close());setInterval(()=>{if(dialog.open)void refresh();},700);
}
