import { SCENARIO_LABELS } from '@shared/mission';

interface DraftCue{id:string;phase:string;at:number;maxDurationSec:number;speaker:string;condition:string;text:{ro:string}}
interface DraftResponse{hash:string;draft:{scenarioId:string;cues:DraftCue[]}}
export function createPackageEditor(dialog:HTMLDialogElement,canEdit:()=>boolean):void{
  const tab=document.createElement('button');tab.type='button';tab.dataset.missionTab='editor';tab.setAttribute('aria-pressed','false');tab.textContent='Editor scenarii';dialog.querySelector('.mission-tabs')?.append(tab);
  const panel=document.createElement('section');panel.dataset.missionPanel='editor';panel.hidden=true;
  panel.innerHTML=`<h3>Dialogul fiecărei experiențe</h3><p>Editezi draftul unui pachet. Modificarea textului invalidează vocea corespunzătoare; pachetul trebuie produs și verificat din nou înainte de public.</p><div class="package-editor-selectors"><label>Experiența<select id="package-edit-profile">${Object.entries(SCENARIO_LABELS).filter(([id])=>id!=='legacy-v3').map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><label>Replica<select id="package-edit-cue"><option>Se încarcă…</option></select></label></div><form id="package-edit-form"><p id="package-edit-meta" class="mission-help"></p><label>Text rostit<textarea id="package-edit-text" rows="5" maxlength="1200"></textarea></label><label class="package-edit-time">Moment în fază (secunde)<input id="package-edit-at" type="number" step="0.1" min="-10" max="465" required /></label><div class="mission-wall-actions"><button id="package-edit-save" type="submit" class="mission-primary">Salvează draftul</button><button id="package-edit-reload" type="button">Reîncarcă de pe server</button></div></form><p id="package-edit-status" role="status"></p>`;
  dialog.querySelector('.mission-dialog-body')?.append(panel);
  const el=<T extends HTMLElement>(id:string)=>panel.querySelector<T>(`#${id}`)!;
  let current:DraftResponse|null=null,request=0,saving=false;
  const note=(text:string)=>{el('package-edit-status').textContent=text;};
  async function api<T>(url:string,body?:unknown):Promise<T>{const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await response.json().catch(()=>({reason:'Răspuns invalid.'}));if(!response.ok||data.ok===false)throw new Error(data.reason??`Eroare ${response.status}`);return data as T;}
  function renderCue():void{const cue=current?.draft.cues.find(c=>c.id===el<HTMLSelectElement>('package-edit-cue').value);el<HTMLButtonElement>('package-edit-save').disabled=saving||!cue||!canEdit();if(!cue)return;el<HTMLTextAreaElement>('package-edit-text').value=cue.text.ro;el<HTMLInputElement>('package-edit-at').value=String(cue.at);el('package-edit-meta').textContent=`${cue.speaker} · ${cue.phase} · slot ${cue.maxDurationSec} s · ${cue.condition}`;}
  async function load():Promise<void>{const generation=++request;const id=el<HTMLSelectElement>('package-edit-profile').value;note('Se încarcă draftul…');current=null;el<HTMLButtonElement>('package-edit-save').disabled=true;try{const response=await api<DraftResponse>(`/api/scenarios/${encodeURIComponent(id)}/draft`);if(generation!==request)return;current=response;el<HTMLSelectElement>('package-edit-cue').replaceChildren(...response.draft.cues.map(cue=>{const option=document.createElement('option');option.value=cue.id;option.textContent=`${cue.at}s · ${cue.speaker} · ${cue.text.ro.slice(0,55)}`;return option;}));renderCue();note(`Draft încărcat · revizia ${response.hash.slice(0,12)}. Editorul original rămâne în Instrumente.`);}catch(err){if(generation===request)note(err instanceof Error?err.message:String(err));}}
  tab.addEventListener('click',()=>{if(!current)void load();});el('package-edit-profile').addEventListener('change',()=>void load());el('package-edit-cue').addEventListener('change',renderCue);el('package-edit-reload').addEventListener('click',()=>void load());
  el('package-edit-form').addEventListener('submit',event=>{event.preventDefault();if(!current||saving||!canEdit())return;const id=current.draft.scenarioId,hash=current.hash,cueId=el<HTMLSelectElement>('package-edit-cue').value,text=el<HTMLTextAreaElement>('package-edit-text').value,at=Number(el<HTMLInputElement>('package-edit-at').value);saving=true;el<HTMLButtonElement>('package-edit-save').disabled=true;void api(`/api/scenarios/${encodeURIComponent(id)}/draft`,{expectedHash:hash,cueId,text,at}).then(async()=>{await load();note('Draft salvat cu backup. Verifică și regenerează vocea modificată înainte de folosire.');}).catch(err=>note(err instanceof Error?err.message:String(err))).finally(()=>{saving=false;el<HTMLButtonElement>('package-edit-save').disabled=!current||!canEdit();});});
  window.setInterval(()=>{el<HTMLButtonElement>('package-edit-save').disabled=saving||!current||!canEdit();},500);
}
