import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {page,renderer,sleep} from './glass-cdp.mjs';
const dir='runs/debug/glass-r5/after';await fs.mkdir(dir,{recursive:true});
const p=await page('http://127.0.0.1:4321/login/');const metrics=[];
const inspect=`(()=>{const d=document.documentElement;const visible=e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(e).visibility!=='hidden'};return {url:location.pathname,theme:d.dataset.theme,width:innerWidth,height:innerHeight,scrollWidth:d.scrollWidth,scrollHeight:d.scrollHeight,images:[...document.images].filter(visible).map(e=>({src:e.getAttribute('src'),ok:e.complete&&e.naturalWidth>0})),smallTargets:[...document.querySelectorAll('button,a,input,select')].filter(visible).map(e=>({text:(e.textContent||e.getAttribute('aria-label')||e.id).trim().slice(0,60),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})).filter(e=>e.w<64||e.h<64)}})()`;
for(const [w,h] of [[1920,1080],[1440,900]]){await p.size(w,h);for(const route of ['login','control','debug','analytics']){await p.call('Page.navigate',{url:`http://127.0.0.1:4321/${route}/`});await sleep(1600);if(route==='login'){await p.shot(`${dir}/login-${w}.png`);continue}metrics.push(await p.eval(inspect));await p.shot(`${dir}/${route}-${w}.png`)}}
await p.size(1920,1080);await p.call('Page.navigate',{url:'http://127.0.0.1:4321/shared/preview.html'});await sleep(1500);for(const theme of ['prologue','launch','light','nature','tech','void','home','white']){await p.eval(`document.querySelectorAll('.themes button')[${['prologue','launch','light','nature','tech','void','home','white'].indexOf(theme)}].click()`);await sleep(450);await p.shot(`${dir}/preview-${theme}.png`)}
await p.call('Page.navigate',{url:'http://127.0.0.1:4321/tablet/'});await sleep(1500);await p.eval(`localStorage.removeItem('nava.tablet.post.v3');location.reload()`);await sleep(1200);metrics.push(await p.eval(inspect));await p.shot(dir+'/tablet-post-assign.png');
await p.call('Page.navigate',{url:'http://127.0.0.1:4321/tablet/?post=1'});await sleep(1500);metrics.push(await p.eval(inspect));await p.shot(dir+'/tablet-waiting.png');
await fs.writeFile(dir+'/metrics-initial.json',JSON.stringify(metrics,null,2));p.close();
const r=await renderer();await r.size(3840,2160);await sleep(1000);await r.shot(dir+'/tv-idle-3840.png');await r.size(1600,900);await sleep(500);await r.shot(dir+'/tv-idle-windowed.png');r.close();console.log('Initial integrated captures ready');
